### ISSUE TITLE
Users should not be able to override other users' processes

### ISSUE THREAD

**Issue by mstajdohar** [genialis/resolwe#173]
Consider this example. We register processes from resolwe-bio as admin. Everyone can later add a process with the same slug, but higher version and so overrides the original process. We should prohibit that.

**Comment by mstajdohar** [comment]
@dblenkus, please share your thoughts on this security issue.

**Comment by mstajdohar** [comment]
This fix will remove the following concern, raised by @jkokosar: process versions keep getting increased when you update the process from Python SDK and they are a lot higher than the versions in the Resolwe Bio. Users should not be able to override the existing processes (unless they know what they are doing, _i.e._ they are the authors).

**Comment by dblenkus** [comment]
I think that we should define broader concept how process should be handled. At the moment all processes are registered with first superuser and that's it (this was quick solution that was enough till now), so we don't have anything to fix, rather implement desired logic.
And on the other hand, we should rethink how resdk uploads new processes because current solution is probably not the best.
