### ISSUE TITLE
Workflow test status

### ISSUE THREAD

**Issue by mzganec** [genialis/resolwe#278]
@dblenkus Workflow tests finish with status OK even though a child process fails. Workflow tests should fail when a child process fails.

**Comment by mstajdohar** [comment]
This was a design choice, because it was easier to implement the workflow this way. So the workflow process starts all child processes and finishes (even if the child processes have not finished yet). At that point the workflow process has completed its task (to run jobs) successfully. We are thinking of implementing control statements into the workflow language. We will probably need to refactor the workflow for this to wait for the child process results. At that point we may choose to change the workflow status behavior.

**Comment by mstajdohar** [comment]
cc @jkokosar

**Comment by kostko** [comment]
This is the correct behaviour as the parent workflow process is considered done when it spawns all children and produces a list of their identifiers as output. The parent doesn't wait for all the children to finish.
